export const MINIMIZE_CHAT = 'MINIMIZE_CHAT';
export const MAXIMIZE_CHAT = 'MAXIMIZE_CHAT';

export const LOAD_ACCOUNT_INFO = 'LOAD_ACCOUNT_INFO';
export const LOAD_ACCOUNT_INFO_SUCCESS = 'LOAD_ACCOUNT_INFO_SUCCESS';
export const LOAD_ACCOUNT_INFO_FAIL = 'LOAD_ACCOUNT_INFO_FAIL';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
export const UPDATE_MESSAGE_FAIL = "UPDATE_MESSAGE_FAIL";

export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS';
export const JOIN_CHANNEL_FAIL = 'JOIN_CHANNEL_FAIL';

export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';
export const LEAVE_CHANNEL_SUCCESS = 'LEAVE_CHANNEL_SUCCESS';
export const LEAVE_CHANNEL_FAIL = 'LEAVE_CHANNEL_FAIL';

export const UPDATE_CHANNEL_LAST_VISITED = 'UPDATE_CHANNEL_LASTVISITED';
export const UPDATE_CHANNEL_LAST_VISITED_SUCCESS = 'UPDATE_CHANNEL_LASTVISITED_SUCCESS';
export const UPDATE_CHANNEL_LAST_VISITED_FAIL = 'UPDATE_CHANNEL_LASTVISITED_FAIL';

export const USER_JOIN = 'USER_JOIN';
export const USER_LEAVE = 'USER_LEAVE';

export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';

export const APPLY_FILTER = 'APPLY_FILTER';

export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
