export const LOAD_ACCOUNT_INFO = 'LOAD_ACCOUNT_INFO';
export const LOAD_ACCOUNT_INFO_SUCCESS = 'LOAD_ACCOUNT_INFO_SUCCESS';
export const LOAD_ACCOUNT_INFO_FAIL = 'LOAD_ACCOUNT_INFO_FAIL';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
